### ISSUE TITLE
New Idea, don't know how to do that

### ISSUE THREAD

**Issue by labamichnetvoll** [lyqyd/Touchpoint#1]
Hello Lyqyd,
your touchpoint api is very nice!
But I have a new idea to get into the api.
It would be very nice, if you can hide and show buttons without removing them. i have tried to work in this feature but i've failed.
can you help me with this?

Would be very nice!
[touchpoint_change.txt](https://github.com/lyqyd/Touchpoint/files/3927654/touchpoint_change.txt)

**Comment by lyqyd** [comment]
Thank you for your interest in Touchpoint!

Because Touchpoint is designed to be a light and simple API, it makes no attempt to do anything with the screen contents other than draw the buttons to it. In order to hide a button, Touchpoint would need to draw something to the screen to replace that button--but it has no idea what should be there instead. I see that your start on the code would have it draw a blank black space, but what if the rest of the screen had a light blue background, for example?

This feature is outside the scope of this project, so I will not be adding it. You are, of course, welcome to branch the project and add the feature for your own use. You'll need to look into using a frame buffer of some sort (perhaps [framebuffer](https://github.com/lyqyd/framebuffer), which I use in other projects) to capture what is on the screen under the buttons, so that you can re-draw that when the buttons are hidden.
